top_srcdir   = /root/apache+php/httpd-2.2.29
top_builddir = /root/apache+php/httpd-2.2.29
srcdir       = /root/apache+php/httpd-2.2.29/srclib
builddir     = /root/apache+php/httpd-2.2.29/srclib
VPATH        = /root/apache+php/httpd-2.2.29/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
