top_srcdir   = /root/apache+php/httpd-2.2.29
top_builddir = /root/apache+php/httpd-2.2.29
srcdir       = /root/apache+php/httpd-2.2.29/server/mpm/worker
builddir     = /root/apache+php/httpd-2.2.29/server/mpm/worker
VPATH        = /root/apache+php/httpd-2.2.29/server/mpm/worker

LTLIBRARY_NAME    = libworker.la
LTLIBRARY_SOURCES = worker.c fdqueue.c pod.c

include $(top_srcdir)/build/ltlib.mk
