top_srcdir   = /root/apache+php/httpd-2.2.29
top_builddir = /root/apache+php/httpd-2.2.29
srcdir       = /root/apache+php/httpd-2.2.29/modules/loggers
builddir     = /root/apache+php/httpd-2.2.29/modules/loggers
VPATH        = /root/apache+php/httpd-2.2.29/modules/loggers

include $(top_srcdir)/build/special.mk

