top_srcdir   = /root/apache+php/httpd-2.2.29
top_builddir = /root/apache+php/httpd-2.2.29
srcdir       = /root/apache+php/httpd-2.2.29/os/unix
builddir     = /root/apache+php/httpd-2.2.29/os/unix
VPATH        = /root/apache+php/httpd-2.2.29/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
