top_srcdir   = /root/apache+php/httpd-2.2.29
top_builddir = /root/apache+php/httpd-2.2.29
srcdir       = /root/apache+php/httpd-2.2.29/modules/metadata
builddir     = /root/apache+php/httpd-2.2.29/modules/metadata
VPATH        = /root/apache+php/httpd-2.2.29/modules/metadata

include $(top_srcdir)/build/special.mk

