top_srcdir   = /root/apache+php/httpd-2.2.29
top_builddir = /root/apache+php/httpd-2.2.29
srcdir       = /root/apache+php/httpd-2.2.29/server/mpm
builddir     = /root/apache+php/httpd-2.2.29/server/mpm
VPATH        = /root/apache+php/httpd-2.2.29/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
