top_srcdir   = /root/apache+php/httpd-2.2.29
top_builddir = /root/apache+php/httpd-2.2.29
srcdir       = /root/apache+php/httpd-2.2.29/modules/echo
builddir     = /root/apache+php/httpd-2.2.29/modules/echo
VPATH        = /root/apache+php/httpd-2.2.29/modules/echo

include $(top_srcdir)/build/special.mk

