top_srcdir   = /root/apache+php/httpd-2.2.29
top_builddir = /root/apache+php/httpd-2.2.29
srcdir       = /root/apache+php/httpd-2.2.29/os
builddir     = /root/apache+php/httpd-2.2.29/os
VPATH        = /root/apache+php/httpd-2.2.29/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
