top_srcdir   = /root/apache+php/httpd-2.2.29
top_builddir = /root/apache+php/httpd-2.2.29
srcdir       = /root/apache+php/httpd-2.2.29/modules/filters
builddir     = /root/apache+php/httpd-2.2.29/modules/filters
VPATH        = /root/apache+php/httpd-2.2.29/modules/filters

include $(top_srcdir)/build/special.mk

