top_srcdir   = /root/apache+php/httpd-2.2.29
top_builddir = /root/apache+php/httpd-2.2.29
srcdir       = /root/apache+php/httpd-2.2.29/modules/aaa
builddir     = /root/apache+php/httpd-2.2.29/modules/aaa
VPATH        = /root/apache+php/httpd-2.2.29/modules/aaa

include $(top_srcdir)/build/special.mk

