top_srcdir   = /root/apache+php/httpd-2.2.29
top_builddir = /root/apache+php/httpd-2.2.29
srcdir       = /root/apache+php/httpd-2.2.29/modules/cache
builddir     = /root/apache+php/httpd-2.2.29/modules/cache
VPATH        = /root/apache+php/httpd-2.2.29/modules/cache

include $(top_srcdir)/build/special.mk

