top_srcdir   = /root/apache+php/httpd-2.2.29
top_builddir = /root/apache+php/httpd-2.2.29
srcdir       = /root/apache+php/httpd-2.2.29/modules/mappers
builddir     = /root/apache+php/httpd-2.2.29/modules/mappers
VPATH        = /root/apache+php/httpd-2.2.29/modules/mappers

include $(top_srcdir)/build/special.mk

